spring:

  datasource:
  #  url: jdbc:mysql://localhost:3306/discapp?serverTimezone=UTC
  #  username: root
  #  password: password

    url: jdbc:postgresql://localhost:5432/discapp
    username: postgres
    password: password


  #  testWhileIdle: true
  #  validationQuery: select 1

  jpa:
    show-sql: false

server:
  port: 8081