spring:

  datasource:
  #  url: jdbc:mysql://localhost:3306/discapp?serverTimezone=UTC
  #  username: root
  #  password: password

    url: jdbc:postgresql://localhost:5432/discapp
    username: postgres
    password: password

  #  testWhileIdle: true
  #  validationQuery: select 1

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true


server:
  port: 8081