spring:

  # h2:
  #  console:
  #    enabled: true

  # h2 connect url: jdbc:h2:mem:testdb
  # h2 console: http://localhost:8081/h2-console/


  datasource:
  #  url: jdbc:mysql://localhost:3306/discapp?serverTimezone=UTC
  #  username: root
  #  password: password

    url: jdbc:postgresql://localhost:5432/discapp
    username: postgres
    password: password

  #  url: jdbc:postgres://ydzhitbwcsixba:409e9ad28ef600fc4d01c17d8b05aa874a50e876aa965cf1de370f7bd21cb1a4@ec2-107-21-120-104.compute-1.amazonaws.com:5432/d9ol8g0nn0aa91
  #  username: ydzhitbwcsixba
  #  password: 409e9ad28ef600fc4d01c17d8b05aa874a50e876aa965cf1de370f7bd21cb1a4

  #  testWhileIdle: true
  #  validationQuery: select 1

  jpa:
    show-sql: false
  #  hibernate:

  #    ddl-auto: update
  #   naming-strategy: org.hibernate.cfg
  #  properties:
  #    hibernate:
  #      dialect: org.hibernate.dialect.MySQLServer

server:
  port: 8081