
spring.mail.properties.mail.smtp.starttls.enable: true

spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: nediscapp@gmail.com
    password: ojxzoxwavsktvbzq
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    #  url: jdbc:mysql://localhost:3306/discapp?serverTimezone=UTC
    #  username: root
    #  password: password

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      idle-timeout: 1000
      pool-name: discapp_pool

    url: jdbc:postgresql://localhost:5432/discapp
    username: postgres
    password: password
    maxActive: 10
    maxIdle: 5
    removeAbandoned: true

  #  testWhileIdle: true
  #  validationQuery: select 1

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true

logging:
  level:
    org:
      springframework:
        web: WARN
      hibernate: WARN
    io:
      github:
        shamrice:
          discapp: INFO

server:
  port: 8081
  servlet:
    session:
      cookie:
        max-age: 14d
      timeout: 1d

discapp:
  auth.remember-me:
    key: 0223c51a-56cc-4a4d-94eb-d5a140e75552
    token.duration: 2592000
  notifier:
    url: https://nediscapp-notifier.herokuapp.com/
    send-hour: 5
  root:
    email: nediscapp@gmail.com
  cache:
    duration: 900000
  security:
    bcrypt:
      strength: 5
