spring.mail.properties.mail.smtp.starttls.enable: true

spring:

  mail:
    host: ${EMAIL_SMTP_HOST}
    port: ${EMAIL_SMTP_PORT}
    username: ${NOTIFICATION_EMAIL_ADDRESS}
    password: ${NOTIFICATION_PASSWORD}
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    #  url: jdbc:mysql://localhost:3306/discapp?serverTimezone=UTC
    #  username: root
    #  password: password

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: ${MAX_DB_CONNECTION_POOL_SIZE}
      idle-timeout: 1000
      pool-name: discapp_pool

    url: jdbc:postgresql://localhost:5432/discapp
    username: postgres
    password: password
    maxActive: ${MAX_DB_ACTIVE_CONNECTIONS}
    maxIdle: ${MAX_DB_IDLE_CONNECTIONS}
    removeAbandoned: true

  #  testWhileIdle: true
  #  validationQuery: select 1

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true

logging:
  level:
    org:
      springframework:
        web: ${LOG_LEVEL_SPRING_WEB}
      hibernate: ${LOG_LEVEL_HIBERNATE}
    io:
      github:
        shamrice:
          discapp: ${LOG_LEVEL_DISCAPP}

server:
  port: 8081
  servlet:
    session:
      cookie:
        max-age: ${COOKIE_MAX_AGE}
      timeout: ${SESSION_TIME_OUT}

discapp:
  auth.remember-me:
    key: ${REMEMBER_ME_PRIVATE_KEY}
    token.duration: ${REMEMBER_ME_TOKEN_DURATION}
  notifier:
    url: ${NOTIFIER_URL}
    send-hour: ${NOTIFIER_SEND_HOUR}
  root:
    email: ${ROOT_EMAIL_ADDRESS}
  cache:
    duration: ${CACHE_DURATION}
  security:
    bcrypt:
      strength: ${BCRYPT_STRENGTH}
